port: /dev/neo-s300-1
baud: 500000
inverted: false
frame_id: /sick_s300_laser_front_link
scan_id: 8
scan_intervals: [[-1.919862177, 1.919862177]] #[rad] these intervals are included to the scan 110Â°
