#robot's geometric parameters:

#Diameter of std. mecanum wheel
wheelDiameter: 0.254
#Length of the mobile robot from wheel center to wheel center
robotLength: 0.475
#Width from wheel center to wheel center
robotWidth: 0.548
#stddev vel x
devX: 0.447
#stddev vel y
devY: 0.447
#stddev vel z
devZ: 0.447
#stddev vel roll
devRoll: 0.447
#stddev vel pitch
devPitch: 0.447
#stddev vel x yaw
devYaw: 0.447